// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	uuid "github.com/google/uuid"
)

type PgtasksTaskIcon string

const (
	PgtasksTaskIconMark        PgtasksTaskIcon = "mark"
	PgtasksTaskIconHome        PgtasksTaskIcon = "home"
	PgtasksTaskIconJob         PgtasksTaskIcon = "job"
	PgtasksTaskIconSupermarket PgtasksTaskIcon = "supermarket"
	PgtasksTaskIconCafe        PgtasksTaskIcon = "cafe"
	PgtasksTaskIconActivity    PgtasksTaskIcon = "activity"
	PgtasksTaskIconDrive       PgtasksTaskIcon = "drive"
	PgtasksTaskIconFlight      PgtasksTaskIcon = "flight"
	PgtasksTaskIconStar        PgtasksTaskIcon = "star"
	PgtasksTaskIconFlag        PgtasksTaskIcon = "flag"
	PgtasksTaskIconHospital    PgtasksTaskIcon = "hospital"
	PgtasksTaskIconOutdoor     PgtasksTaskIcon = "outdoor"
)

func (e *PgtasksTaskIcon) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PgtasksTaskIcon(s)
	case string:
		*e = PgtasksTaskIcon(s)
	default:
		return fmt.Errorf("unsupported scan type for PgtasksTaskIcon: %T", src)
	}
	return nil
}

type NullPgtasksTaskIcon struct {
	PgtasksTaskIcon PgtasksTaskIcon
	Valid           bool // Valid is true if PgtasksTaskIcon is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPgtasksTaskIcon) Scan(value interface{}) error {
	if value == nil {
		ns.PgtasksTaskIcon, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PgtasksTaskIcon.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPgtasksTaskIcon) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PgtasksTaskIcon), nil
}

func (e PgtasksTaskIcon) Valid() bool {
	switch e {
	case PgtasksTaskIconMark,
		PgtasksTaskIconHome,
		PgtasksTaskIconJob,
		PgtasksTaskIconSupermarket,
		PgtasksTaskIconCafe,
		PgtasksTaskIconActivity,
		PgtasksTaskIconDrive,
		PgtasksTaskIconFlight,
		PgtasksTaskIconStar,
		PgtasksTaskIconFlag,
		PgtasksTaskIconHospital,
		PgtasksTaskIconOutdoor:
		return true
	}
	return false
}

type PgtasksTaskPriority string

const (
	PgtasksTaskPriorityLow    PgtasksTaskPriority = "low"
	PgtasksTaskPriorityMedium PgtasksTaskPriority = "medium"
	PgtasksTaskPriorityHigh   PgtasksTaskPriority = "high"
)

func (e *PgtasksTaskPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PgtasksTaskPriority(s)
	case string:
		*e = PgtasksTaskPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for PgtasksTaskPriority: %T", src)
	}
	return nil
}

type NullPgtasksTaskPriority struct {
	PgtasksTaskPriority PgtasksTaskPriority
	Valid               bool // Valid is true if PgtasksTaskPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPgtasksTaskPriority) Scan(value interface{}) error {
	if value == nil {
		ns.PgtasksTaskPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PgtasksTaskPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPgtasksTaskPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PgtasksTaskPriority), nil
}

func (e PgtasksTaskPriority) Valid() bool {
	switch e {
	case PgtasksTaskPriorityLow,
		PgtasksTaskPriorityMedium,
		PgtasksTaskPriorityHigh:
		return true
	}
	return false
}

type PgtasksTaskStatus string

const (
	PgtasksTaskStatusPending   PgtasksTaskStatus = "pending"
	PgtasksTaskStatusCompleted PgtasksTaskStatus = "completed"
)

func (e *PgtasksTaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PgtasksTaskStatus(s)
	case string:
		*e = PgtasksTaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PgtasksTaskStatus: %T", src)
	}
	return nil
}

type NullPgtasksTaskStatus struct {
	PgtasksTaskStatus PgtasksTaskStatus
	Valid             bool // Valid is true if PgtasksTaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPgtasksTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PgtasksTaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PgtasksTaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPgtasksTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PgtasksTaskStatus), nil
}

func (e PgtasksTaskStatus) Valid() bool {
	switch e {
	case PgtasksTaskStatusPending,
		PgtasksTaskStatusCompleted:
		return true
	}
	return false
}

type PgtasksTask struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	GroupID         *uuid.UUID
	Assignees       []uuid.UUID
	Title           string
	Description     string
	Location        interface{}
	IsFavorite      bool
	Priority        string
	Status          string
	Icon            string
	Deadline        *time.Time
	NotifyAt        []time.Time
	CompletedAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PurgeAt         *time.Time
	TitleLang       string
	DescriptionLang string
	SearchVector    interface{}
}
