// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/twpayne/go-geom"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE pgtasks.task
SET status = $2,
    completed_at = $3,
    updated_at = $4
WHERE id = $1
`

type CompleteTaskParams struct {
	ID          uuid.UUID
	Status      string
	CompletedAt *time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.Exec(ctx, completeTask,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.UpdatedAt,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO pgtasks.task (
                  id, owner_id,
                  group_id, title,
                  description, location,
                  is_favorite, priority,
                  icon, status,
                  deadline, notify_at,
                  title_lang, description_lang
)
VALUES (
        $1, $2,
        $3, $4,
        $5, $6::geometry,
        $7, $8,
        $9, $10,
        $11, $12,
        $13, $14
)
`

type CreateTaskParams struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	GroupID         *uuid.UUID
	Title           string
	Description     string
	Column6         *geom.Point
	IsFavorite      bool
	Priority        string
	Icon            string
	Status          string
	Deadline        *time.Time
	NotifyAt        []time.Time
	TitleLang       string
	DescriptionLang string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.OwnerID,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.Column6,
		arg.IsFavorite,
		arg.Priority,
		arg.Icon,
		arg.Status,
		arg.Deadline,
		arg.NotifyAt,
		arg.TitleLang,
		arg.DescriptionLang,
	)
	return err
}

const deleteTasksByOwnerID = `-- name: DeleteTasksByOwnerID :exec
DELETE FROM pgtasks.task WHERE owner_id = $1
`

func (q *Queries) DeleteTasksByOwnerID(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTasksByOwnerID, ownerID)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, owner_id,
       group_id, title,
       description, ST_AsBinary(location)::geometry AS location,
       is_favorite, priority,
       icon, status,
       deadline, notify_at,
       created_at, updated_at,
       completed_at, purge_at
FROM pgtasks.task WHERE id = $1
LIMIT 1
`

type GetTaskByIDRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	GroupID     *uuid.UUID
	Title       string
	Description string
	Location    *geom.Point
	IsFavorite  bool
	Priority    string
	Icon        string
	Status      string
	Deadline    *time.Time
	NotifyAt    []time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt *time.Time
	PurgeAt     *time.Time
}

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IsFavorite,
		&i.Priority,
		&i.Icon,
		&i.Status,
		&i.Deadline,
		&i.NotifyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PurgeAt,
	)
	return i, err
}

const restoreTask = `-- name: RestoreTask :exec
UPDATE pgtasks.task
SET updated_at = $2, purge_at = NULL
WHERE id = $1
`

type RestoreTaskParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) RestoreTask(ctx context.Context, arg RestoreTaskParams) error {
	_, err := q.db.Exec(ctx, restoreTask, arg.ID, arg.UpdatedAt)
	return err
}

const saveTask = `-- name: SaveTask :exec
UPDATE pgtasks.task
SET owner_id = $2, group_id = $3,
    title = $4, description = $5,
    location = $6, is_favorite = $7,
    priority = $8, icon = $9,
    status = $10, deadline = $11,
    notify_at = $12, completed_at = $13,
    created_at = $14, updated_at = $15,
    purge_at = $16, title_lang = $17,
    description_lang = $18
WHERE id = $1
`

type SaveTaskParams struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	GroupID         *uuid.UUID
	Title           string
	Description     string
	Location        interface{}
	IsFavorite      bool
	Priority        string
	Icon            string
	Status          string
	Deadline        *time.Time
	NotifyAt        []time.Time
	CompletedAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PurgeAt         *time.Time
	TitleLang       string
	DescriptionLang string
}

func (q *Queries) SaveTask(ctx context.Context, arg SaveTaskParams) error {
	_, err := q.db.Exec(ctx, saveTask,
		arg.ID,
		arg.OwnerID,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.IsFavorite,
		arg.Priority,
		arg.Icon,
		arg.Status,
		arg.Deadline,
		arg.NotifyAt,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PurgeAt,
		arg.TitleLang,
		arg.DescriptionLang,
	)
	return err
}

const softDeleteTaskByID = `-- name: SoftDeleteTaskByID :exec
UPDATE pgtasks.task
SET purge_at = $2, updated_at = $3
WHERE id = $1
`

type SoftDeleteTaskByIDParams struct {
	ID        uuid.UUID
	PurgeAt   *time.Time
	UpdatedAt time.Time
}

func (q *Queries) SoftDeleteTaskByID(ctx context.Context, arg SoftDeleteTaskByIDParams) error {
	_, err := q.db.Exec(ctx, softDeleteTaskByID, arg.ID, arg.PurgeAt, arg.UpdatedAt)
	return err
}
