version: '2'

linters:
  default: 'none'
  enable:
    - 'errcheck'
    - 'govet'
    - 'unused'
    - 'asciicheck'
    - 'bidichk'
    - 'copyloopvar'
    - 'embeddedstructfieldcheck'
    - 'errname'
    - 'errorlint'
    - 'gocheckcompilerdirectives'
    - 'gocritic'
    - 'godoclint'
    - 'modernize'
    - 'nestif'
    - 'nonamedreturns'
    - 'perfsprint'
    - 'prealloc'
    - 'predeclared'
    - 'promlinter'
    - 'spancheck'
    - 'unconvert'
    - 'unparam'
    - 'whitespace'
    - 'zerologlint'

run:
  timeout: '5m'
  tests: true
