all: false
filename: mocks_test.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
template: testify
packages:
  task-service/internal/infrastructure/mongo:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mocks_{{.InterfaceName}}.go'
      pkgname: 'mocks'
    interfaces:
      TaskClient:
  task-service/internal/domain/task:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
    interfaces:
      Repository:
