edition = "2023";

package jbat.tap.v1.task;

import "google/protobuf/timestamp.proto";
import "google/api/field_behavior.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

message SearchTasksResponse {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      title: "SearchTasksResponse",
      description: "Transfer the information about tasks with their ids.",
      required: [
        "ids",
        "next_sync_key"
      ]
    }

    example: '{"ids":["123e4567-e89b-12d3-a456-426614174001"],"next_sync_key":"2024-12-31T23:59:59Z"}'
  };

  repeated string ids = 1 [
    json_name = "ids",
    (google.api.field_behavior) = REQUIRED,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      title: "ids",
      description: "Array of UUIDs that representing the search result.",
      required: "true",
      format: "array",
      example: '["123e4567-e89b-12d3-a456-426614174001"]'
    }
  ];

  google.protobuf.Timestamp next_sync_key = 2 [
    json_name = "next_sync_key",
    (google.api.field_behavior) = REQUIRED,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      title: "next_sync_key",
      description: "Timestamp of the last retrieved task from the ids array. Client should pass this value in the next request to find new tasks.",
      required: "true",
      format: "date-time",
      example: '"2024-12-31T23:59:59Z"'
    }
  ];
}
