// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// NewMockTaskClient creates a new instance of MockTaskClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskClient {
	mock := &MockTaskClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskClient is an autogenerated mock type for the TaskClient type
type MockTaskClient struct {
	mock.Mock
}

type MockTaskClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskClient) EXPECT() *MockTaskClient_Expecter {
	return &MockTaskClient_Expecter{mock: &_m.Mock}
}

// Database provides a mock function for the type MockTaskClient
func (_mock *MockTaskClient) Database() *mongo.Database {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 *mongo.Database
	if returnFunc, ok := ret.Get(0).(func() *mongo.Database); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Database)
		}
	}
	return r0
}

// MockTaskClient_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type MockTaskClient_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
func (_e *MockTaskClient_Expecter) Database() *MockTaskClient_Database_Call {
	return &MockTaskClient_Database_Call{Call: _e.mock.On("Database")}
}

func (_c *MockTaskClient_Database_Call) Run(run func()) *MockTaskClient_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskClient_Database_Call) Return(database *mongo.Database) *MockTaskClient_Database_Call {
	_c.Call.Return(database)
	return _c
}

func (_c *MockTaskClient_Database_Call) RunAndReturn(run func() *mongo.Database) *MockTaskClient_Database_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MockTaskClient
func (_mock *MockTaskClient) Disconnect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockTaskClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskClient_Expecter) Disconnect(ctx interface{}) *MockTaskClient_Disconnect_Call {
	return &MockTaskClient_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *MockTaskClient_Disconnect_Call) Run(run func(ctx context.Context)) *MockTaskClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskClient_Disconnect_Call) Return(err error) *MockTaskClient_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskClient_Disconnect_Call) RunAndReturn(run func(ctx context.Context) error) *MockTaskClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockTaskClient
func (_mock *MockTaskClient) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockTaskClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskClient_Expecter) Ping(ctx interface{}) *MockTaskClient_Ping_Call {
	return &MockTaskClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockTaskClient_Ping_Call) Run(run func(ctx context.Context)) *MockTaskClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskClient_Ping_Call) Return(err error) *MockTaskClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskClient_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockTaskClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
