// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// newMocktaskClient creates a new instance of mocktaskClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktaskClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktaskClient {
	mock := &mocktaskClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktaskClient is an autogenerated mock type for the taskClient type
type mocktaskClient struct {
	mock.Mock
}

type mocktaskClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktaskClient) EXPECT() *mocktaskClient_Expecter {
	return &mocktaskClient_Expecter{mock: &_m.Mock}
}

// Database provides a mock function for the type mocktaskClient
func (_mock *mocktaskClient) Database() *mongo.Database {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 *mongo.Database
	if returnFunc, ok := ret.Get(0).(func() *mongo.Database); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Database)
		}
	}
	return r0
}

// mocktaskClient_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type mocktaskClient_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
func (_e *mocktaskClient_Expecter) Database() *mocktaskClient_Database_Call {
	return &mocktaskClient_Database_Call{Call: _e.mock.On("Database")}
}

func (_c *mocktaskClient_Database_Call) Run(run func()) *mocktaskClient_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocktaskClient_Database_Call) Return(database *mongo.Database) *mocktaskClient_Database_Call {
	_c.Call.Return(database)
	return _c
}

func (_c *mocktaskClient_Database_Call) RunAndReturn(run func() *mongo.Database) *mocktaskClient_Database_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type mocktaskClient
func (_mock *mocktaskClient) Disconnect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocktaskClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type mocktaskClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mocktaskClient_Expecter) Disconnect(ctx interface{}) *mocktaskClient_Disconnect_Call {
	return &mocktaskClient_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *mocktaskClient_Disconnect_Call) Run(run func(ctx context.Context)) *mocktaskClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktaskClient_Disconnect_Call) Return(err error) *mocktaskClient_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocktaskClient_Disconnect_Call) RunAndReturn(run func(ctx context.Context) error) *mocktaskClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type mocktaskClient
func (_mock *mocktaskClient) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocktaskClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type mocktaskClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mocktaskClient_Expecter) Ping(ctx interface{}) *mocktaskClient_Ping_Call {
	return &mocktaskClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *mocktaskClient_Ping_Call) Run(run func(ctx context.Context)) *mocktaskClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktaskClient_Ping_Call) Return(err error) *mocktaskClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocktaskClient_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *mocktaskClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
