name: 'CI/CD'

on:
  workflow_dispatch: { }

  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ 'main' ]

env:
  NODE_JS_VERSION: 24
  GO_VERSION: '1.26.2'
  GOLANGCI_LINT_VERSION: 'v2.11'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  config:
    runs-on: 'ubuntu-24.04'
    permissions: { }
    outputs:
      linux-runner-image: ${{ steps.constants.outputs.linux-runner-image }}
    steps:
      - name: 'Define constants'
        id: 'constants'
        run: |
          echo "linux-runner-image=ubuntu-24.04" >> $GITHUB_OUTPUT

  lint-commits:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config' ]
    steps:
      - name: 'Clone repository'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v6'
        with:
          node-version: ${{ env.NODE_JS_VERSION }}

      - name: 'Setup commitlint'
        run: npm install -D @commitlint/cli @commitlint/config-conventional

      - name: 'Lint commits'
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
          else
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          fi

  check-changes:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    outputs:
      has-important-changes: ${{ steps.filter.outputs.code }}
    needs: [ 'config', 'lint-commits' ]
    steps:
      - name: 'Clone repository'
        uses: 'actions/checkout@v6'

      - name: 'Check important changes'
        id: 'filter'
        uses: 'dorny/paths-filter@v4'
        with:
          filters: |
            code:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'proto/**'
              - 'Dockerfile'

  go-lint:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'check-changes' ]
    if: needs.check-changes.outputs.has-important-changes == 'true'
    steps:
      - name: 'Clone repository'
        uses: 'actions/checkout@v6'

      - name: 'Setup go'
        uses: 'actions/setup-go@v6'
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 'Setup golang-ci linter'
        uses: 'golangci/golangci-lint-action@v9'
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  build:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'go-lint' ]
    steps:
      - name: 'Clone repository'
        uses: 'actions/checkout@v6'

      - name: 'Setup go'
        uses: 'actions/setup-go@v6'
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 'Build project'
        run: go build ./...

  test:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'build' ]
    steps:
      - name: 'Clone repository'
        uses: 'actions/checkout@v6'

      - name: 'Setup go'
        uses: 'actions/setup-go@v6'
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 'Run tests'
        run: go test ./...
